
version: 2.1
description: "Orange County Lettings"

orbs: 
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Configure virtual environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            source env/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            source env/bin/activate
            python3 manage.py test

 

workflows:
  main:
    jobs:
      - build_and_test
      - docker/publish:
          extra_build_args: '--build-arg SECRET_KEY=$SECRET_KEY'
          image: $DOCKER_LOGIN/final_image_oc_letting_site
          tag: '$CIRCLE_SHA1,latest'
          requires:
            - build_and_test
          filters:
            branches:
              only: master2


      
          