version: 2.1

description: 

orbs: 
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: configure virtual environment
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.
      - run:
          name: Run tests
          command: |
            source env/bin/activate
            python3 manage.py test
      - run:
          name: run flake8
          command: flake8
          