
version: 2.1
description: "Orange County Lettings"

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Configure virtual environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            source env/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            source env/bin/activate
            python3 manage.py test


  containerize:
        docker:
          - image: cimg/python:3.9
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "containerize"
                command: |
                    echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
                    docker build -t final_image_oc_lettings_site .
                    docker tag final_image_oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
                    docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

  deploy:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:login
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:release -a $HEROKU_APP_NAME web
 

workflows:
  main:
    jobs:
      - build_and_test
      - containerize:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - containerize
          filters:
            branches:
              only:
                - main

#sudo curl https://cli-assets.heroku.com/install.sh | sh
 #           HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
  #          HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set SECRET_KEY=$SECRET_KEY -a $HEROKU_APP_NAME
   #         HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=0 -a $HEROKU_APP_NAME
    #        HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
     #       HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web
      #      HEROKU_API_KEY=${HEROKU_TOKEN} heroku run python manage.py migrate -a $HEROKU_APP_NAME
