
version: 2.1
description: "Orange County Lettings"

orbs: 
  docker: circleci/docker@2.0.2

 # heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Configure virtual environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            source env/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            source env/bin/activate
            python3 manage.py test


  containerize:
        docker:
          - image: cimg/python:3.9
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "containerize"
                command: |
                    echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
                    docker build -t final_image_oc_lettings_site .
                    docker tag final_image_oc_lettings_site $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1
                    docker push $DOCKER_LOGIN/$DOCKER_REPO:$CIRCLE_SHA1

 

workflows:
  main:
    jobs:
      - build_and_test
      - containerize:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - circle
  #    jobs:
  #    - build_and_test
  #    - docker/publish:
  #        #extra_build_args: '--build-arg SECRET_KEY=$SECRET_KEY'
  #        image: $DOCKER_LOGIN/$DOCKER_REPO
  #        tag: '$CIRCLE_SHA1'
  #        requires:
  #          - build_and_test
  #        filters:
  #          branches:
  #            only: circle